# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_managers_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managers',
            old_name='CardNo',
            new_name='DollarPurch',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='PayPal',
            new_name='GridsOut',
        ),
        migrations.RenameField(
            model_name='managers',
            old_name='CardType',
            new_name='GridsPurch',
        ),
    ]
