# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20180527_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='DollarPurch',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='managers',
            name='GridsOut',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='managers',
            name='GridsPurch',
            field=models.IntegerField(),
        ),
    ]
