# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20180604_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('UsrName', models.CharField(max_length=20)),
                ('GridsPch', models.IntegerField()),
                ('Amount', models.FloatField(max_length=20)),
            ],
        ),
    ]
