# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-14 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20181205_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='Password',
            field=models.CharField(default=99990000, max_length=25),
        ),
    ]
