# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid2', '0011_auto_20170307_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grid',
            name='accessNumber',
            field=models.CharField(max_length=12),
        ),
    ]
