# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid2', '0012_auto_20190120_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='terms',
            name='GRID',
            field=models.CharField(default=1, max_length=100000),
        ),
    ]
